sudo: required

language: ruby

services:
  - docker

env:
  global:
    - PATH="${PATH}:${HOME}/.local/bin"

install:
  - mkdir -p ~/.local/bin/
  - curl --silent --location git.io/weave --output ~/.local/bin/weave
  - chmod +x ~/.local/bin/weave
  - weave setup

script:
  - weave launch
  - eval $(weave env)
  - docker run --name=pingme --tty --interactive --detach busybox
  - docker run busybox ping -c3 pingme
  - weave report | jq
  - weave status
  - weave status dns
  - eval $(weave env --restore)
  - weave stop
