sudo: false

env:
  - PATH="${PATH}:${HOME}/.local/bin"
  - AWS_DEFAULT_REGION="eu-central-1"

install:
  - pip install --user awscli

script:
  - set -o pipefail
  - aws cloudformation validate-template --template-body "file:////${PWD}/aws/ecs/cloudformation.json" | jq .

deploy:
  provider: s3
  bucket: weaveworks-cfn-public
  access_key_id:
    secure: ONS+E6rthhKPXKZDtt7qdYKfayHLSG1JuGvFD2wirYhBcS/xdQskaE7qB8xUabhI90+ENJbUmd2uG+fNckS2mPMACp6TQ+1R89cNgyU1Z1WXUlGGT6PFtvTAhDehelzOHp27RYBl7JsuUtmayulSbE4zgjfAF4rNok7nMxKALbYTvMT/9yN2q/BUhOwptOu1aTOlncMb6f4Ac8PpEHlz17q+vfp2lpVWXR6U5k5tV5Qma0SUUZAr2ba+Vc1MSiQKDYUHhmA3u45Uen3A+Brp3BNRgGg6Hx+Zu/UgGz2RX/awew5dG8EunbpexLMSWdv9t6Wr4ofJpvtEFDK3bB92k6t6l6Nt2EqsxYCu0tlxM5n32dYMxkaMqwP0tPLHsggZmXK5aNeFT+YZTxiy6CnrTsftyfByzGGaDQ3eTiqtB3aHcXyUNIEkVvBYdrtOtw9WEWOzUydVeT2gJGY1lFZ6difAJ7nBigjQ5oU+OyuNMZzM49/UdK9+CoTyPXG4pSLehnX7GP8NuOzGI/j2t5jSqmgSecCWh4vR4sIs6GxUjgP+mKK3sOB1NN/O6JixTvPjlpxqMaFWZnhFlWDHdoBlwqamNnf8dNLbdaP3dIpUznIIDBsq2XjQeKxmN2FylMSRtQX2f3J7Q13xljsMIjOr+zydm/chy+OfgXWl2ZTRZes=
  secret_access_key:
    secure: lWVis2qfC17VLaYrhvmnDuqfwKxRuS7WELlBMbKmfch+jAis0xzKqTCimZ2VAOlIGTv+OYXzJBuQv82XXZQBimvsbCIOsiMli/o8u4JGHi1535ewh03c7lKesSB5JhqlL6RVEPRPPoJ882MC/oY22ueHhjoSAi7r/OU0AofCrpv9Exw3LBlBwZlDCMErIAeXKUvv9o98HbZSF4/+9rAylbCg2jAmAUslrbu5jWu9bFu1aWeSpC4jxXN0ebvlYyHwBAEyb/g4ADFC/9OzYvsG72/cd2cSu130ayjddw8StWsA6XJ1o3XYz8rghXHKA/vD8y6BY+n29RO1I9+eEhA39y5Bj61XKeYZSQpQZ2tqQvLVneoA3rz9N4VG/xZVTZJ5kNF+rO+EQMjpxLl1l1BhMemRKZv2L3PQSwK1Q/CJZ4mWiZhS08I0koQjU/0Vwk461OdGzfWXizQI7Q535rx9JbWJShPgU6GvsHJ1JUkitYoYFRpWGBPHyVSJvwvTovFePQmL30XC9QVBIh7B/n0QlpH/2CuHcRXxYpQfe+6Yq93LQTf9LZagESSSFHIIn7T7C13yMRhIpa9QkAEQCi0MqNB3G5xzwynCJpZ9sCEb3KcQKHhHTvO7PCl7Qv2Kf8Fp2t8ZMGRd1qhgoXLRALfvp0KlLi8QPNJhQ3atINyEXdQ=
