sudo: false

env:
  global:
    - PATH="${PATH}:${HOME}/.local/bin" AWS_DEFAULT_REGION="eu-central-1"
    - secure: aEub6462B0FB31SUF/1GeM/qsi0eJ6xN6mRRb43Q7iUvzA2Mn/km7V9endU9m5LrxzC32FCNOXfwSasvHMCCOTrDChLBRoT/gR07iWbPCl/a8Ku9yyl13RVZfax1Wtulo3Ugb5T6bTN/WMOLCXwuLJGjE1PYRT134e/K42mQ7Tm1gTiMk1j4O7F9Bfa6znKsT+2ebz1Qy2qWXGubwsgpLLy7ZPgpANJ95L/HCZcs02wYWoqyUrH6X8D9vJ0PWx3szPEWCQd/nigILoPt9DinYCLg3qojQgX69dRezGK1TAd81Q4o7WzE7M6ySoIlpapfExUSKXLE1K+lRj69tkpvgNjo46tQGsbwLVoQXKgzjgHxT8zvnBSL76FQQMIsHoVmFsJH5QVGB8pktZSwsXcRqG8ROV0pI204/IX0zNB02STXB0rVMdjSuL6eVrIQ7dBPzOW25yIA564Q3URSAra8/RwDJidouJWWawZnQ61abXjKroWiOAarmAYWAr5730wwDRnPKzKMndy5tLF7xfsh+VPulhXdprZtjG1ga0VoGqTrncjcBEOZU7KRzGb0+brNllhMlVIi6xDbhoGKhXCcguwmAcucB1M5+9iT/V8AXEmAfKWOHH/MrruVctS0rry3yoLzJUYjC3lgVgJLNXbHKuns+k8zOHXs/5Em7rJVEq4=
    - secure: LsVGcTek2r9Geo5SbdyczufhdyGI10c9BABuu4KtBoP8qeSFiWUhDkDuLpVCrXCsb8YYDwFP1nUqW0s6vvBwujMLObjyFppVYwxqP/71yFXraIApYBnMcherhs7tVHYgSmgD3ANmGWA+dk847sio/otqu5ug+Q8KnAwYIl9Qca2mB5MMlI7mlh3F0s50tAdNaASKsNQ1/y+iytXzU1fnpYxOWTdiSduH5GJeRSD18ROUBGUPAZjTzAgBGPe2SniEX3TI+6C+5hYzXPpwNSJt5R2lB0aBTvt0j0SCaQ4pqp7caEe8TwI7OzWidJowYKK/C7oTD7aDoxgu6528+zuKgVRV8ABIWy/l4CDAPruw6WDStL5q53yfKle12Zq+48PK0hl3rmnL1yzgajtaLuEN1Z1B7MJRFcL1qC6Abw9DRrmbgPkpChFepMGIPWcEzETN075ddycLZCI58doP8Mf3Y26+UncmZPIAkFXBhZJK9jfnYutSPwN4kLoCGsYTDPfBuF9Xee2zuTQUqOhM+G2HYtmZfbnyY/3OwRobvDZvCnWngzR3m5O2Xap5io569gmvn5d5MHu9Qs/YjC5xuQCHfFK2SwZt5m04z+UaV77WNdIWsVY6PYGnGEoMSgIz1NlANU4XVpNNmQTaeikUFLuiAlilq8tEMCr38QlcPaFmlOU=

install:
  - pip install --user awscli

script:
  - set -o pipefail
  - aws cloudformation validate-template --template-body "file:////${PWD}/aws/ecs/cloudformation.json" | jq .

after_success:
  - mkdir cfn-to-publish
  - jq ".Description += \" (weaveworks/integrations@${TRAVIS_COMMIT})\"" "aws/ecs/cloudformation.json" > cfn-to-publish/ecs-baseline.json

deploy:
  provider: s3
  bucket: weaveworks-cfn-public
  skip_cleanup: true
  local_dir: cfn-to-publish
  upload_dir: integrations
  on:
    branch: ci
  access_key_id:
    secure: ONS+E6rthhKPXKZDtt7qdYKfayHLSG1JuGvFD2wirYhBcS/xdQskaE7qB8xUabhI90+ENJbUmd2uG+fNckS2mPMACp6TQ+1R89cNgyU1Z1WXUlGGT6PFtvTAhDehelzOHp27RYBl7JsuUtmayulSbE4zgjfAF4rNok7nMxKALbYTvMT/9yN2q/BUhOwptOu1aTOlncMb6f4Ac8PpEHlz17q+vfp2lpVWXR6U5k5tV5Qma0SUUZAr2ba+Vc1MSiQKDYUHhmA3u45Uen3A+Brp3BNRgGg6Hx+Zu/UgGz2RX/awew5dG8EunbpexLMSWdv9t6Wr4ofJpvtEFDK3bB92k6t6l6Nt2EqsxYCu0tlxM5n32dYMxkaMqwP0tPLHsggZmXK5aNeFT+YZTxiy6CnrTsftyfByzGGaDQ3eTiqtB3aHcXyUNIEkVvBYdrtOtw9WEWOzUydVeT2gJGY1lFZ6difAJ7nBigjQ5oU+OyuNMZzM49/UdK9+CoTyPXG4pSLehnX7GP8NuOzGI/j2t5jSqmgSecCWh4vR4sIs6GxUjgP+mKK3sOB1NN/O6JixTvPjlpxqMaFWZnhFlWDHdoBlwqamNnf8dNLbdaP3dIpUznIIDBsq2XjQeKxmN2FylMSRtQX2f3J7Q13xljsMIjOr+zydm/chy+OfgXWl2ZTRZes=
  secret_access_key:
    secure: lWVis2qfC17VLaYrhvmnDuqfwKxRuS7WELlBMbKmfch+jAis0xzKqTCimZ2VAOlIGTv+OYXzJBuQv82XXZQBimvsbCIOsiMli/o8u4JGHi1535ewh03c7lKesSB5JhqlL6RVEPRPPoJ882MC/oY22ueHhjoSAi7r/OU0AofCrpv9Exw3LBlBwZlDCMErIAeXKUvv9o98HbZSF4/+9rAylbCg2jAmAUslrbu5jWu9bFu1aWeSpC4jxXN0ebvlYyHwBAEyb/g4ADFC/9OzYvsG72/cd2cSu130ayjddw8StWsA6XJ1o3XYz8rghXHKA/vD8y6BY+n29RO1I9+eEhA39y5Bj61XKeYZSQpQZ2tqQvLVneoA3rz9N4VG/xZVTZJ5kNF+rO+EQMjpxLl1l1BhMemRKZv2L3PQSwK1Q/CJZ4mWiZhS08I0koQjU/0Vwk461OdGzfWXizQI7Q535rx9JbWJShPgU6GvsHJ1JUkitYoYFRpWGBPHyVSJvwvTovFePQmL30XC9QVBIh7B/n0QlpH/2CuHcRXxYpQfe+6Yq93LQTf9LZagESSSFHIIn7T7C13yMRhIpa9QkAEQCi0MqNB3G5xzwynCJpZ9sCEb3KcQKHhHTvO7PCl7Qv2Kf8Fp2t8ZMGRd1qhgoXLRALfvp0KlLi8QPNJhQ3atINyEXdQ=
