sudo: false

env:
  - PATH="${PATH}:${HOME}/.local/bin"

install:
  - pip install --user awscli

script:
  - set -o pipefail
  - aws cloudformation validate-template --template-body "file:////${PWD}/aws/ecs/cloudformation.json" | jq .
